import unittest
import solution


class DragonFractalTests(unittest.TestCase):

    def test_dragon_fractal(self):
        sequence = ['up',
                    'left',
                    'down',
                    'left',
                    'down',
                    'right',
                    'down',
                    'left',
                    'down',
                    'right',
                    'up',
                    'right',
                    'down',
                    'right',
                    'down',
                    'left',
                    'down',
                    'right',
                    'up',
                    'right',
                    'up',
                    'left',
                    'up',
                    'right',
                    'down',
                    'right',
                    'up',
                    'right',
                    'down',
                    'right',
                    'down',
                    'left',
                    'down',
                    'right',
                    'up',
                    'right',
                    'up',
                    'left',
                    'up',
                    'right',
                    'up',
                    'left',
                    'down',
                    'left',
                    'up',
                    'left',
                    'up',
                    'right',
                    'down',
                    'right',
                    'up',
                    'right',
                    'up',
                    'left',
                    'up',
                    'right',
                    'down',
                    'right',
                    'up',
                    'right',
                    'down',
                    'right',
                    'down',
                    'left',
                    'down',
                    'right',
                    'up',
                    'right',
                    'up',
                    'left',
                    'up',
                    'right',
                    'up',
                    'left',
                    'down',
                    'left',
                    'up',
                    'left',
                    'up',
                    'right',
                    'up',
                    'left',
                    'down',
                    'left',
                    'down',
                    'right',
                    'down',
                    'left',
                    'up',
                    'left',
                    'down',
                    'left',
                    'up',
                    'left',
                    'up',
                    'right',
                    'down',
                    'right',
                    'up',
                    'right']

        dragon = solution.dragon_fractal()
        for direction in sequence:
            self.assertEqual(direction, next(dragon))

if __name__ == '__main__':
    unittest.main()
